"""Step 9: write REPORT.md from the result files (every number comes from results/).

    .venv/bin/python scripts/09_report.py
"""
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd

from tess_search import DATA, ROOT, RESULTS, vetting


def load_jsonl(name):
    p = RESULTS / "reliability" / f"{name}.jsonl"
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()] if p.exists() else []


def reclassify(sig):
    """Apply the final vetting rules to stored metrics (as 06_summarize does for real data)."""
    if sig.get("vet"):
        return vetting.classify(sig["vet"])[0]
    return sig.get("verdict", "not vetted")


def pct(x):
    return f"{100 * x:.1f}%"


def main():
    targets = pd.read_csv(DATA / "targets.csv")
    index = pd.read_parquet(DATA / "lc_index.parquet")
    summary = json.loads((RESULTS / "summary.json").read_text())
    sig = pd.read_csv(RESULTS / "all_signals.csv")
    cands = pd.read_csv(RESULTS / "candidates.csv")
    known = pd.read_csv(RESULTS / "known_recovery.csv") if (RESULTS / "known_recovery.csv").exists() else None
    follow = pd.read_csv(RESULTS / "followup" / "summary.csv") if (RESULTS / "followup" / "summary.csv").exists() else None

    inj = load_jsonl("inject")
    inv = load_jsonl("invert")
    for r in inj:
        r["passed"] = False
        if r.get("recovered"):
            for s in r["signals"]:
                if abs(s["period"] / r["period"] - 1) < 0.005:
                    r["passed"] = reclassify(s) in ("candidate", "weak candidate")
                    break
    inv_cands = [sum(reclassify(s) == "candidate" for s in r["signals"]) for r in inv]
    inv_weak = [sum(reclassify(s) == "weak candidate" for s in r["signals"]) for r in inv]

    L = []
    w = L.append
    w("# TESS M-dwarf deep search: report\n")
    w(f"*Generated by `scripts/09_report.py` from the files in `results/`.*\n")
    w("## Data\n")
    w(f"* **{len(targets):,} M dwarfs** (Teff <= 3900 K, R <= 0.65 R_sun, TESS mag <= 13.5, low contamination) "
      f"with **>= 20 sectors** of SPOC 2-minute photometry; median {int(targets.n_sectors.median())} sectors, "
      f"max {targets.n_sectors.max()}.")
    w(f"* Chosen from {len(index):,} light-curve files of {index.tic.nunique():,} stars in sectors 1-{index.sector.max()}.")
    w(f"* {summary['stars']:,} stars searched; {summary['signals_total']:,} periodic signals detected; "
      f"{summary['signals_vetted']:,} strong enough to vet.\n")
    w("![sample](results/figures/sample.png)\n")

    w("## Validation on known planets\n")
    if known is not None:
        in_range = known[(known.period >= 0.4) & (known.period <= 40)]
        w(f"{int(in_range.recovered.sum())} of {len(in_range)} catalogued signals with periods 0.4-40 d on the "
          "searched stars were recovered. Unrecovered ones are listed so they can be checked (several are planets "
          "found by radial velocity that do not transit).\n")
        w("| star | known signal | period (d) | disposition | recovered | verdict |")
        w("|---|---|---|---|---|---|")
        for _, r in in_range.sort_values(["tic", "period"]).iterrows():
            w(f"| TIC {r.tic} | {r['name']} | {r.period:.4f} | {r.disposition} | {'yes' if r.recovered else 'no'} | "
              f"{r.verdict if isinstance(r.verdict, str) else ''} |")
        w("")

    w("## Completeness: injected planets\n")
    if inj:
        df = pd.DataFrame(inj)
        w(f"{len(df)} synthetic planets (batman model, 0.6-4 R_earth, 0.5-40 d, random impact parameter) were "
          "planted into the raw light curves of randomly chosen stars without known planets, then the full pipeline "
          "was run.\n")
        w(f"* detected at the right period and epoch: **{pct(df.recovered.mean())}**")
        w(f"* detected **and** passed vetting: **{pct(df.passed.mean())}**")
        rec = df[df.recovered]
        if len(rec):
            w(f"* of the detected ones, vetting kept {pct(rec.passed.mean())} (the rest is the price of rejecting "
              "false positives)\n")
        for lo, hi in [(0.6, 1.5), (1.5, 2.5), (2.5, 4.0)]:
            for plo, phi in [(0.5, 5), (5, 15), (15, 40)]:
                m = (df.rp >= lo) & (df.rp < hi) & (df.period >= plo) & (df.period < phi)
                if m.sum() >= 3:
                    w(f"  * {lo}-{hi} R_earth, {plo}-{phi} d: {pct(df[m].passed.mean())} (n={m.sum()})")
        w("\n![completeness](results/figures/completeness.png)\n![snr](results/figures/snr_recovery.png)\n")

    w("## Reliability: inverted light curves\n")
    if inv:
        w(f"{len(inv)} light curves were flipped upside down (dips become bumps) and searched with the same "
          "pipeline. Nothing in flipped data can be a planet, so anything that passes vetting is a false alarm.\n")
        w(f"* stars with a false **candidate**: {sum(c > 0 for c in inv_cands)} of {len(inv)} "
          f"({pct(np.mean([c > 0 for c in inv_cands]))}); total false candidates {sum(inv_cands)}")
        w(f"* stars with a false **weak candidate**: {sum(c > 0 for c in inv_weak)} of {len(inv)}")
        rate = sum(inv_cands) / len(inv)
        w(f"* scaled to the {summary['stars']:,} searched stars this predicts ~{rate * summary['stars']:.0f} false "
          f"candidates in the real search.\n")

    w("## Results\n")
    w("| verdict | signals |")
    w("|---|---|")
    for k, v in sorted(summary["verdicts"].items(), key=lambda x: -x[1]):
        w(f"| {k} | {v} |")
    w("\nMost common reasons for rejection:\n")
    for k, v in list(summary["fp_reason_counts"].items())[:12]:
        w(f"* {k}: {v}")
    w("\n![verdicts](results/figures/verdicts.png)\n")
    w("Signals that passed vetting, by what they match:\n")
    for k, v in summary["novelty_of_passed"].items():
        w(f"* {k}: {v}")
    w("")

    w("## Candidates not in any catalogue\n")
    if follow is not None and len(follow):
        w("Each was re-vetted from scratch, checked against Gaia DR3 neighbours (could a nearby star make the "
          "dip?) and searched for independently in each half of the data.\n")
        w("| TIC | period (d) | depth (ppm) | radius (R_earth) | SNR | verdict | in both halves | Gaia neighbours that could mimic it | RUWE |")
        w("|---|---|---|---|---|---|---|---|---|")
        for _, r in follow.sort_values("snr_red", ascending=False).iterrows():
            w(f"| {r.tic} | {r.period:.5f} | {r.depth_ppm:.0f} | {r.rp_rearth:.2f} | {r.snr_red:.1f} | {r.verdict} | "
              f"{'yes' if r.in_both_halves else 'no'} | {r.gaia_possible_sources} | {r.ruwe} |")
        w("\nDiagnostic sheets: `results/followup/TIC<id>_<n>.png`.\n")
    else:
        w("None survived.\n")
    (ROOT / "REPORT.md").write_text("\n".join(L))
    print("wrote REPORT.md")


if __name__ == "__main__":
    main()
