"""Step 9: write REPORT.md from the result files (every number comes from results/).

    .venv/bin/python scripts/09_report.py

The only hand-written parts are the per-candidate assessments in NOTES, which
summarise what I saw on each candidate's diagnostic sheet and follow-up page.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd

from tess_search import DATA, ROOT, RESULTS, vetting

NOTES = {
    (32090583, 5): "A **third periodic signal on TOI-218**, a star with two known TESS candidates (0.438 d and 8.352 d), "
                   "found after both were masked. Its period is not a simple ratio of either (4.90 and 3.89). Not in any "
                   "TOI, CTOI or SPOC TCE list. Extra candidates in systems that already have planets are statistically "
                   "much more likely to be real. ExoFOP lists two high-resolution imaging observations of this star.",
    (229689348, 1): "An **11.2-hour orbit** with a crisp, flat-bottomed transit (SDE 15, 1,088 transits) and the "
                    "cleanest vetting metrics of the set. Flagged by SPOC in three multi-sector runs (s14-50, s14-55, "
                    "s14-86) but never made a TOI; nothing on ExoFOP.",
    (198412174, 1): "Clean on every test and present in both halves, but cautions: the transit is short (impact parameter "
                    "~0.93), SPOC's SNR for the same period fell as data were added (8.5, 6.0, 4.4 for s14-50, s14-78, "
                    "s14-86) although this search finds ~10 on the same sectors, and a star 6 mag fainter sits 4.7\" away, "
                    "unresolved by TESS (an 11%-deep eclipsing binary there would mimic the signal).",
    (294053492, 1): "Not in any catalogue. Cautions: the dip is somewhat V-shaped, the depth in pre-PDC (SAP) flux is "
                    "lower (833 vs 1,107 ppm), and the field is crowded (17 Gaia neighbours bright enough to mimic it).",
    (149390648, 1): "Flagged by SPOC as a TCE but never a TOI. Weakest of the five: the first half of the data alone does not "
                    "lock onto the period, and the field is very crowded (27 Gaia neighbours bright enough to mimic it).",
}


def load_jsonl(name):
    p = RESULTS / "reliability" / f"{name}.jsonl"
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()] if p.exists() else []


def reclassify(sig):
    """Apply the final vetting rules to stored metrics (as 06_summarize does for real data)."""
    if sig.get("vet"):
        return vetting.classify(sig["vet"])[0]
    return sig.get("verdict", "not vetted")


def pct(x):
    return f"{100 * x:.1f}%"


def main():
    targets = pd.read_csv(DATA / "targets.csv")
    index = pd.read_parquet(DATA / "lc_index.parquet")
    summary = json.loads((RESULTS / "summary.json").read_text())
    known = pd.read_csv(RESULTS / "known_recovery.csv")
    follow = pd.read_csv(RESULTS / "followup" / "summary.csv")
    confirmed = pd.read_csv(DATA / "catalogs" / "confirmed.csv")
    transiting = dict(zip(confirmed.pl_name, confirmed.tran_flag))

    inj = load_jsonl("inject")
    inv = load_jsonl("invert")
    for r in inj:
        r["passed"] = False
        if r.get("recovered"):
            s = next((s for s in r["signals"] if abs(s["period"] / r["period"] - 1) < 0.005), None)
            r["passed"] = bool(s) and reclassify(s) in ("candidate", "weak candidate")
    inj_df = pd.DataFrame(inj)
    inv_cands = [sum(reclassify(s) == "candidate" for s in r["signals"]) for r in inv]
    inv_weak = [sum(reclassify(s) == "weak candidate" for s in r["signals"]) for r in inv]

    in_range = known[(known.period >= 0.4) & (known.period <= 40)].copy()
    in_range["transits"] = [transiting.get(n, 1) if s == "CONFIRMED" else 1 for n, s in zip(in_range["name"], in_range.source)]
    conf = in_range[in_range.source == "CONFIRMED"]
    conf_tr = conf[conf.transits == 1]
    can_transit = in_range[(in_range.transits == 1) & (in_range.disposition != "FA")]

    full = follow[follow.verdict == "candidate"].copy()
    weak = follow[follow.verdict == "weak candidate"].copy()
    fits = {}
    for _, r in follow.iterrows():
        info = json.loads((RESULTS / "followup" / f"TIC{r.tic}_{r.signal}.json").read_text())
        fits[(r.tic, r.signal)] = info

    L = []
    w = L.append
    w("# TESS M-dwarf deep search: report\n")
    w("*Generated by `scripts/09_report.py` from the files in `results/`; candidate assessments are mine.*\n")

    # ------------------------------------------------------------ key findings
    w("## Key findings\n")
    w(f"* Searched the **{summary['stars']:,} bright M dwarfs** that TESS has watched longest (>= 20 sectors, through "
      f"sector {index.sector.max()}) for transiting planets with periods of 0.4-40 days.")
    w(f"* The pipeline independently recovers **{len(conf_tr[conf_tr.recovered])} of {len(conf_tr)} confirmed transiting "
      f"planets** in that range (and {int(can_transit.recovered.sum())} of {len(can_transit)} catalogued signals that can "
      "transit), including all four planets of TOI-700, and passes them through vetting.")
    big = (inj_df.rp >= 2) & (inj_df.period < 15)
    small = (inj_df.rp < 1.5) & (inj_df.period < 5)
    w(f"* **Completeness** ({len(inj_df)} injected planets): {pct(inj_df.recovered.mean())} detected, "
      f"{pct(inj_df.passed.mean())} detected and passed vetting; {pct(inj_df[big].passed.mean())} for planets of "
      f"2-4 R_earth inside 15 days, {pct(inj_df[small].passed.mean())} for planets under 1.5 R_earth inside 5 days.")
    w(f"* **Reliability** (200 flipped light curves): **no false candidates** (95% upper limit "
      f"{pct(3 / len(inv))} of stars); false *weak* candidates on {pct(np.mean([c > 0 for c in inv_weak]))} of stars.")
    w(f"* **{len(full)} candidates that are in no planet catalogue** passed every test and deeper follow-up "
      f"({sum(full.novelty == 'new')} appear in no list at all, {sum(full.novelty != 'new')} were flagged by NASA's "
      "pipeline but never promoted), all Earth-sized (about 1.0-1.3 R_earth) on orbits shorter than 3 days. "
      f"{len(weak)} weaker signals are listed separately; most are expected to be false alarms.\n")

    w("## Candidates\n")
    w("Each was re-vetted from scratch, fitted with a physical transit model (batman, quadratic limb darkening fixed, "
      "stellar-density prior), checked against Gaia DR3 neighbours, and searched for independently in each half of "
      "the data. A candidate is a signal worth follow-up observations, **not a confirmed planet**.\n")
    w("| TIC | period (d) | mid-transit (BJD) | depth (ppm) | radius (R_earth) | impact b | T14 (h) | SNR | both halves | RUWE | status |")
    w("|---|---|---|---|---|---|---|---|---|---|---|")
    for _, r in full.sort_values("snr_red", ascending=False).iterrows():
        f = fits[(r.tic, r.signal)]["fit"]
        status = "new (no list)" if r.novelty == "new" else "SPOC TCE, never a TOI"
        w(f"| {r.tic} | {f['period']:.6f} | {f['t0_bjd']:.4f} | {f['depth_ppm']:.0f} | {f['rp_rearth']:.2f} ± "
          f"{f['rp_rearth_err']:.2f} | {f['b']:.2f} | {f['t14_h']:.2f} | {r.snr_red:.1f} | "
          f"{'yes' if r.in_both_halves else 'partly'} | {r.ruwe:.2f} | {status} |")
    w("\n*Radius errors exclude the uncertainty of the stellar radius (TIC v8.2).*\n")
    for _, r in full.sort_values("snr_red", ascending=False).iterrows():
        w(f"**TIC {r.tic}.** {NOTES.get((r.tic, r.signal), '')} "
          f"Dossier: `results/followup/TIC{r.tic}_{r.signal}.md`, sheet: `results/followup/TIC{r.tic}_{r.signal}.png`.\n")
    w("What would settle each one: ground-based photometry during predicted transits (to see which star dims), "
      "high-resolution imaging, and radial velocities or statistical validation. Each dossier has the ephemeris and "
      "parameters a community-TOI (CTOI) submission to ExoFOP asks for.\n")

    # ------------------------------------------------------------ data
    w("## Data\n")
    w(f"* **{len(targets):,} M dwarfs** (Teff <= 3900 K, R <= 0.65 R_sun, TESS mag <= 13.5, low contamination) with "
      f"**>= 20 sectors** of SPOC 2-minute photometry; median {int(targets.n_sectors.median())} sectors, max "
      f"{targets.n_sectors.max()}.")
    w(f"* Chosen from {len(index):,} light-curve files of {index.tic.nunique():,} stars in sectors 1-{index.sector.max()}. "
      "NASA's latest combined multi-sector search covered sectors 1-96.")
    w(f"* {summary['signals_total']:,} periodic signals detected; {summary['signals_vetted']:,} strong enough to vet.\n")
    w("![sample](results/figures/sample.png)\n")

    # ------------------------------------------------------------ validation
    w("## Validation on known planets\n")
    w(f"Of {len(in_range)} catalogued signals with periods 0.4-40 d on the searched stars, "
      f"{int(in_range.recovered.sum())} were recovered. Of the {len(in_range) - int(in_range.recovered.sum())} missed, "
      f"{len(conf) - len(conf_tr)} are confirmed planets found by radial velocity that **do not transit** "
      "(no transit search can see them) and one is a known false alarm. The real misses:\n")
    miss = in_range[(~in_range.recovered) & (in_range.transits == 1) & (in_range.disposition != "FA")]
    w("| star | signal | period (d) | disposition |")
    w("|---|---|---|---|")
    for _, r in miss.sort_values("period").iterrows():
        w(f"| TIC {r.tic} | {r['name']} | {r.period:.4f} | {r.disposition} |")
    rec = in_range[in_range.recovered]
    w(f"\nOf the recovered signals, vetting passed {int((rec.verdict == 'candidate').sum() + (rec.verdict == 'weak candidate').sum())} "
      f"and rejected {int((rec.verdict == 'false positive').sum())}; the rejected ones include signals the TESS team itself "
      "classified as false positives (e.g. TOI-419.01, TOI-1178.01, TOI-1635.01). The full table is in the appendix.\n")

    # ------------------------------------------------------------ completeness
    w("## Completeness: injected planets\n")
    w(f"{len(inj_df)} synthetic planets (0.6-4 R_earth, 0.5-40 d, random impact parameter) were planted into the raw "
      "light curves of random stars without known planets, and the full pipeline was run on each.\n")
    w(f"* detected at the right period and epoch: **{pct(inj_df.recovered.mean())}**; detected and passed vetting: "
      f"**{pct(inj_df.passed.mean())}** (vetting kept {pct(inj_df[inj_df.recovered].passed.mean())} of detected planets; "
      "most losses are planets with periods within 3% of the spacecraft's 13.7-day orbit or its multiples, which are "
      "rejected on purpose).")
    for lo, hi in [(0.6, 1.0), (1.0, 1.5), (1.5, 2.0), (2.0, 3.0), (3.0, 4.0)]:
        m = (inj_df.rp >= lo) & (inj_df.rp < hi)
        w(f"  * {lo}-{hi} R_earth: {pct(inj_df[m].passed.mean())} found and kept (n={m.sum()})")
    w("\n![completeness](results/figures/completeness.png)\n")

    # ------------------------------------------------------------ reliability
    w("## Reliability: inverted light curves\n")
    w(f"{len(inv)} light curves were flipped upside down (dips become bumps) and searched with the same pipeline. "
      "Nothing in flipped data can be a planet, so anything that passes vetting is a false alarm.\n")
    w(f"* false **candidates**: {sum(inv_cands)} on {sum(c > 0 for c in inv_cands)} of {len(inv)} stars. With none seen, "
      f"at 95% confidence fewer than {pct(3 / len(inv))} of stars produce one (fewer than ~{3 / len(inv) * summary['stars']:.0f} "
      f"expected among the {summary['stars']:,} searched stars; best estimate close to none).")
    wr = np.mean([c > 0 for c in inv_weak])
    w(f"* false **weak candidates**: on {pct(wr)} of stars, i.e. ~{wr * summary['stars']:.0f} expected among the searched "
      f"stars, against {summary['verdicts'].get('weak candidate', 0)} found in the real search. **Weak candidates are therefore mostly false alarms.**\n")

    # ------------------------------------------------------------ results overview
    w("## What happened to every signal\n")
    w("| verdict | signals |")
    w("|---|---|")
    for k, v in sorted(summary["verdicts"].items(), key=lambda x: -x[1]):
        w(f"| {k} | {v} |")
    w("\nMost common reasons for rejection (a signal can have several):\n")
    for k, v in list(summary["fp_reason_counts"].items())[:12]:
        w(f"* {k}: {v}")
    w("\n![verdicts](results/figures/verdicts.png)\n")

    w("## Weak candidates\n")
    w(f"Passed the hard tests but with flags (usually modest red-noise SNR or uneven transit depths). The inversion test "
      f"predicts about {wr * summary['stars']:.0f} false weak candidates in this sample, so treat these as a list to "
      "re-check with more data, not as candidates.\n")
    w("| TIC | period (d) | depth (ppm) | radius (R_earth) | SNR | both halves | RUWE | flags |")
    w("|---|---|---|---|---|---|---|---|")
    for _, r in weak.sort_values("snr_red", ascending=False).iterrows():
        w(f"| {r.tic} | {r.period:.4f} | {r.depth_ppm:.0f} | {r.rp_rearth:.2f} | {r.snr_red:.1f} | "
          f"{'yes' if r.in_both_halves else 'no'} | {r.ruwe:.2f} | {r.reasons} |")
    w("")

    # ------------------------------------------------------------ appendix
    w("## Appendix: every catalogued signal on the searched stars (0.4-40 d)\n")
    w("| star | known signal | period (d) | disposition | transits | recovered | verdict |")
    w("|---|---|---|---|---|---|---|")
    for _, r in in_range.sort_values(["tic", "period"]).iterrows():
        w(f"| TIC {r.tic} | {r['name']} | {r.period:.4f} | {r.disposition} | {'yes' if r.transits else 'no (RV)'} | "
          f"{'yes' if r.recovered else 'no'} | {r.verdict if isinstance(r.verdict, str) else ''} |")
    (ROOT / "REPORT.md").write_text("\n".join(L) + "\n")
    print("wrote REPORT.md")


if __name__ == "__main__":
    main()
